apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: orders-service-deployment
spec:
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      namespace: development
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: mel0man/kstore-orders-service:v1
        env:
          - name: OrdersService_DatabaseConnections__Orders__Password
            valueFrom:
              secretKeyRef:
                name: orders-secret
                key: orders-db-password
          - name: OrdersService_DatabaseConnections__Orders__UserId
            value: OrderUser
          - name: OrdersService_DatabaseConnections__Orders__Server
            value: db-service.development
          - name: OrdersService_DatabaseConnections__Orders__Port
            value: '1433'
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
---
apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: orders-service-endpoint
spec:
  type: LoadBalancer
  selector:
    app: orders-service
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https

